### ISSUE TITLE
Not reading my config file

### ISSUE THREAD

**Issue by MaicolBen** [getsentry/onpremise#575] opened 2020-07-10 16:36 UTC
So my production server outputs the example file at `/etc/sentry/config.yml` and it says that variables aren't set (if I set them manually in the console works), some of them don't exist (e.g. `slack.signing-secret`) if I do `sentry config list` . What could I be doing wrong?

**Comment by BYK** [comment] 2020-07-10 18:37
I think you are not using our provided setup and forgetting to set `SENTRY_CONF=/etc/sentry` as we do in https://github.com/getsentry/onpremise/blob/9d44b99c5521239971a4be397fe68c9c3f0ac4f3/docker-compose.yml#L25

**Comment by MaicolBen** [comment] 2020-07-10 19:01
I have that in the docker compose, should I have something different?

**Comment by BYK** [comment] 2020-07-10 19:22
Are you using this repo without modifications?

**Comment by MaicolBen** [comment] 2020-07-10 19:29
I modified:
- the dockerfile with `FROM sentry:latest` as it was failing with `Please provide a source image with from prior to commit`
- copied sentry/config.yml and made my changes, they aren't reflected in the instance
- copied sentry/sentry.conf.yml, they aren't reflected in the instance either

The last 2 I tried adding them in the root of the repo, nothing happens. This was working in version 8.21

**Comment by BYK** [comment] 2020-07-10 21:03
>the dockerfile with FROM sentry:latest as it was failing with Please provide a source image with from prior to commit

This is your issue. This current version is for Sentry 20.6.0+. When you try to use `sentry:latest` it is actually fetching Sentry 9.1.2. If you want to use that, please use the [9.1.2 tag](https://github.com/getsentry/onpremise/tree/9.1.2) on this repo. Then you should not need to change anything in the Dockerfile too.

**Comment by MaicolBen** [comment] 2020-07-13 14:08
That error happened with 91.2 as well, I had to fix the sentry image. And the reported issue happens to me with 9.1.2 too.

**Comment by BYK** [comment] 2020-07-13 16:15
Yes as the 9.1.2 image and that version of this repo requires rebuilding the image for configuration to be updated.

Closing as this is expected behavior (albeit not great) for this old version.

**Closed by BYK** 2020-07-13 16:15 UTC
Labels: needs-info

**Comment by BYK** [comment] 2020-07-13 17:06
@MaicolBen oh, sorry sure! (didn't realize that was the part you're struggling with)

Just running `./install.sh` again while you are on the [9.1.2 tag](https://github.com/getsentry/onpremise/tree/9.1.2?rgh-link-date=2020-07-10T21%3A03%3A41Z) should do it. Otherwise you'd need to run `docker-compose build web cron worker` and then `docker-compose down` and finally `docker-compose up -d` again.

I know this is a bit cumbersome, and that's why we switched to the new volume-based system for newer versions where all you need to do is to run `docker-compose restart web cron worker` (or just `docker-compose restart`).

**Comment by MaicolBen** [comment] 2020-07-13 21:54
I guess the release 20* isn't in the docker registry yet, I rather use the last way as I don't manage the infrastructure and I cannot run those commands. I will hold on this until `slack.signing-secret` is added to the default config file so at least I can configure it inside the server (because as I said it isn't overriding with my config).

Thanks and sorry for the troubles caused.

**Comment by BYK** [comment] 2020-07-13 23:22
>I guess the release 20* isn't in the docker registry yet,

They are here: https://hub.docker.com/r/getsentry/sentry/tags?page=1&name=20.

>I will hold on this until slack.signing-secret is added to the default config file so at least I can configure it inside the server (because as I said it isn't overriding with my config).

Not sure if you can configure this from the UI but it is available on `config.yml`: https://github.com/getsentry/onpremise/blob/bb2b37a06585e503fa1a8abe4f67222398585c0a/sentry/config.example.yml#L101

>Thanks and sorry for the troubles caused.

Not at all 🙂

**Comment by MaicolBen** [comment] 2020-07-14 15:44
> Not sure if you can configure this from the UI but it is available on config.yml:

That's the issue I posted, I cannot do that. But I can configure it in the server with `sentry config set`

**Comment by BYK** [comment] 2020-07-14 18:38
>But I can configure it in the server with sentry config set

Yeah, I'd still recommend using the `config.yml` file but up to you.

**Comment by MaicolBen** [comment] 2020-07-20 18:38
As I said I my instance isn't using it, maybe works with recent versions. I cannot pull images > 9.1.2 with specific tags (e.g. `1485c5aca7ef6381e55abb21625f0e107edf1203`) because "Could not reach any registry endpoint", if you know when you will publish a 20x tag, reply this thread. If not, thanks anyway.

**Comment by BYK** [comment] 2020-07-21 12:03
@MaicolBen we have been releasing 20.x versions since June, latest is 20.7.1 released a few days ago. The config file changes and the volume mount is done on this repo so you need to use this repo (not referring to the docker images).

If you need to use the Docker image directly (definitely not recommended), make sure your `FROM` section says `getsentry/sentry:20.7.2`, not `sentry:20.7.2`. Note the `getsentry/` part at the beginning, it is important.

**Comment by MaicolBen** [comment] 2020-07-21 14:27
That worked! But bumped into #468,  so nothing else to say here
