### ISSUE TITLE
Non-interactive installation hangs on EC2 instance

### ISSUE THREAD

**Issue by theintz** [getsentry/onpremise#946] opened 2021-05-08 13:10 UTC
### Version Information

Version: 21.4.1

Docker versions:
```
# docker-compose version
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

# docker version
Client:
 Version:           20.10.4
 API version:       1.41
 Go version:        go1.15.8
 Git commit:        d3cb89e
 Built:             Mon Mar 29 18:54:36 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.4
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.8
  Git commit:       363e9a8
  Built:            Mon Mar 29 18:55:03 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Linux version:
```
# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

### Steps to Reproduce

My cloud-init scripts tries to download and install sentry onpremise like so:
```
SENTRY_URL="https://github.com/getsentry/onpremise/archive/refs/tags/21.4.1.tar.gz"
curl -sSL $SENTRY_URL -o /tmp/sentry.tar.gz
mkdir /sentry && cd /sentry
tar -xzf /tmp/sentry.tar.gz --strip-components=1

./install.sh --no-user-prompt
```

### Expected Result

Installation finishes successfully as when called manually.

### Actual Result

The install script hangs at the `Setting up zookeeper` stage and never finishes.

### Logs

The last couple of lines from the install logs:
```
Docker images built.

<E2><96><B6> Turning things off ...
--no-ansi option is deprecated and will be removed in future versions. Use `--ansi never` instead.
Removing network onpremise_default
Network onpremise_default not found.
--no-ansi option is deprecated and will be removed in future versions. Use `--ansi never` instead.
Removing network sentry_onpremise_default
Network sentry_onpremise_default not found.

<E2><96><B6> Setting up Zookeeper ...
--no-ansi option is deprecated and will be removed in future versions. Use `--ansi never` instead.
Creating network "sentry_onpremise_default" with the default driver
Creating volume "sentry_onpremise_sentry-secrets" with default driver
Creating volume "sentry_onpremise_sentry-smtp" with default driver
Creating volume "sentry_onpremise_sentry-zookeeper-log" with default driver
Creating volume "sentry_onpremise_sentry-kafka-log" with default driver
Creating volume "sentry_onpremise_sentry-smtp-log" with default driver
Creating volume "sentry_onpremise_sentry-clickhouse-log" with default driver
Creating sentry_onpremise_zookeeper_run ...
Creating sentry_onpremise_zookeeper_run ... done
```

This is the output of `ps fax`:
```
 2631 ?        Ss     0:00 /usr/bin/python /usr/bin/cloud-init modules --mode=final
 2649 ?        S      0:00  \_ tee -a /var/log/cloud-init-output.log
 2650 ?        S      0:00  \_ /bin/bash /var/lib/cloud/instance/scripts/part-001
 7739 ?        S      0:00      \_ bash ./install.sh --no-user-prompt
 7743 ?        S      0:00          \_ bash ./install.sh --no-user-prompt
 7744 ?        S      0:00          |   \_ tee -a sentry_install_log-2021-05-08_12-50-21.txt
11016 ?        S      0:00          \_ bash ./install.sh --no-user-prompt
11017 ?        S      0:00              \_ docker-compose --no-ansi run --rm zookeeper bash -c ls 2>/dev/null -Ubad1 -- /var/lib/zookeeper/data/version-2 | wc -l | tr -d [:space:]
11018 ?        S      0:00                  \_ docker-compose --no-ansi run --rm zookeeper bash -c ls 2>/dev/null -Ubad1 -- /var/lib/zookeeper/data/version-2 | wc -l | tr -d [:space:]
11066 ?        Sl     0:00                      \_ /usr/bin/docker start --attach --interactive f99e8842db38e374813d0d8e6fc9e5a02f13ae8594a4826022de45e1b92b7548
```

I also ran strace to maybe see what was going on:
```
# strace -p 11066
strace: Process 11066 attached
futex(0x560cb91934e0, FUTEX_WAIT_PRIVATE, 0, NULL^Cstrace: Process 11066 detached
 <detached ...>
```

**Comment by BYK** [comment] 2021-05-10 10:17
This is what we run during the zookeeper setup phase: https://github.com/getsentry/onpremise/blob/master/install/set-up-zookeeper.sh

Nothing too fancy. Is it possible for you to turn on debug logging for `bash` to see more details?

**Comment by theintz** [comment] 2021-05-13 15:51
It looks like the script is hanging during the execution of this like: https://github.com/getsentry/onpremise/blob/master/install/set-up-zookeeper.sh#L3

I've tried executing it manually, which works just fine. Annoyingly the install script itself runs just fine when invoked manually on the shell.

Do you mean to turn on `set +x` for bash?

**Comment by BYK** [comment] 2021-05-13 17:55
Pretty sure this is due to the same issue with #951. Closing this one as duplicate of #951 as that one has better information to address the issue.

Apologies for the inconvenience and thanks a lot for the report and patience!

**Closed by BYK** 2021-05-13 17:55 UTC
Labels: Status: Needs More Information

**Comment by pharindoko** [comment] 2021-05-22 05:47
Same issue still appears with 21.5.1.
