### ISSUE TITLE
Sentry does not install/upgrade in Amazon Linux 2

### ISSUE THREAD

**Issue by christopherowen** [getsentry/onpremise#1080] opened 2021-08-31 11:07 UTC
### Environment

self-hosted (`onpremise` deployment)

### Version

21.8.0

### Steps to Reproduce

- git pull origin 21.8.0
- ./install.sh

### Expected Result

The product should update itself

### Actual Result

FAIL: Expected minimum docker-compose version to be 1.28.0 but found 1.26.0

**Comment by chadwhitacre** [comment] 2021-08-31 12:34
Mostly a duplicate of #1062. You'll need to up `docker-compose` in your environment, @christopherowen. Feel free to post notes here for others on Amazon Linux 2 to discover.

Good luck! :-)

**Closed by chadwhitacre** 2021-08-31 12:34 UTC
Labels: Status: Untriaged

**Comment by christopherowen** [comment] 2021-08-31 12:51
this script did the trick for me:

```
#!/bin/bash
sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```
