### ISSUE TITLE
i have set everythis as document, but i still can't send email

### ISSUE THREAD

**Issue by weirui88888** [getsentry/onpremise#1090] opened 2021-09-09 08:49 UTC
### Version

21.9.0

### this is my config.yml，ant i think my config is rigiht

```javascript
mail.backend: 'smtp'
mail.host: 'smtp.qq.com'
mail.port: 25
mail.username: 'xxx@qq.com'
mail.password: 'xxx'
mail.use-tls: false
# The email address to send on behalf of
mail.from: 'xxx@qq.com'
```

### but i find that my `Email Addresses` like this，the status is unverified,I tried to click the button on the right, but it doesn’t seem to work
![WechatIMG44](https://user-images.githubusercontent.com/23164664/132652065-6a114672-fb22-4ad5-8bfe-fd1c08f000f3.jpeg)

### when i try to send a email,an error is `[Errno 101] Network is unreachable `
![WechatIMG47](https://user-images.githubusercontent.com/23164664/132653264-ba4d9d9d-054a-4d39-9e35-d9c07ac733af.jpeg)

---

# this is what i want to know
1.what i should do to verify my emial address?
2.error tips about `[Errno 101] Network is unreachable` due to i don't verify my emial address?

please give me some help, please!:cry:

### Expected Result

i hope i can send error issue to my email!

### Actual Result

I'm very upset becase i can't !

**Comment by BYK** [comment] 2021-09-09 08:51
>.error tips about [Errno 101] Network is unreachable due to i don't verify my emial address?

This indicates that your Sentry instance is not able to communicate with the mail server you've set. Closing the issue as this is not a bug on our end.

You'll need to ensure your Docker network is allowed to communicate with your mail server. Moreover, I recommend not using port 25 as it is usually blocked by ISPs. Also not using SSL or TLS is not a good idea.

**Closed by BYK** 2021-09-09 08:51 UTC
Labels: Status: Untriaged

**Comment by weirui88888** [comment] 2021-09-09 08:56
> > .error tips about [Errno 101] Network is unreachable due to i don't verify my emial address?
> 
> This indicates that your Sentry instance is not able to communicate with the mail server you've set. Closing the issue as this is not a bug on our end.
> 
> You'll need to ensure your Docker network is allowed to communicate with your mail server. Moreover, I recommend not using port 25 as it is usually blocked by ISPs. Also not using SSL or TLS is not a good idea.

thanks!
