### ISSUE TITLE
Upgrading to recent install.sh with nginx/relay blocked incoming events - relay errors

### ISSUE THREAD

**Issue by Apollon77** [getsentry/onpremise#520] opened 2020-05-30 16:12 UTC
I upgraded to the latest onpremise today. I came from an earlier version without nginx and relay

The system it self was running but no new events came in. The nginx log was ok and I saw http status 200 for  new crash reports. But still nothing appered in the system.

I then checked the relay log and found this:

```
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:57:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:23Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream,
  caused by: Server disconnected,
  caused by: Server disconnected,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:26Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information,
  caused by: failed to fetch project state from upstream,
2020-05-30T15:58:28Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated,
2020-05-30T15:58:29Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated,
2020-05-30T15:58:30Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated,
2020-05-30T15:58:33Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated,
2020-05-30T15:58:36Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated,
2020-05-30T15:58:41Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated,
2020-05-30T15:58:44Z [relay_server::utils::shutdown] ERROR: Dropped unfinished future during shutdown: process_event,
2020-05-30T15:58:44Z [relay_server::utils::shutdown] ERROR: Dropped unfinished future during shutdown: process_event,
```

The initial first install.sh run created the new nginx and relay "files" and also logged this. Subsequent install.sh calls only had no more logs about relay.

In the end I now remived nginx and relay again ( I knid of reverted https://github.com/getsentry/onpremise/commit/e97da7c56f28532a29864876ec2fc58921691d6b#diff-4e5e90c6228fd48698d074241c2ba760) and so it works well.

If interesting: I use the system with another nginx (ok in fact Synology reverse proxy service) to add https for calls from the outside

**Comment by BYK** [comment] 2020-06-02 16:42
>Subsequent install.sh calls only had no more logs about relay.

This is by design.

>In the end I now remived nginx and relay again ( I knid of reverted e97da7c#diff-4e5e90c6228fd48698d074241c2ba760) and so it works well.

This will stop working soon as event ingestion code will be removed from Sentry.

Seems like Relay was having a hard time communicating with Sentry web service. Do you have logs from that to share here?

**Comment by Apollon77** [comment] 2020-06-02 20:08
I wil try it again and to get log the next days

**Comment by Apollon77** [comment] 2020-06-07 17:35
Ok, I retried, I did a fresh install.hs Upgrade og my installaton and also fetched most current status from Github.

Relay log
```
2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:34Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:25:35Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated


2020-06-07T17:25:36Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated


2020-06-07T17:25:38Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated


2020-06-07T17:25:40Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated


2020-06-07T17:25:44Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated


2020-06-07T17:25:49Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated


2020-06-07T17:25:57Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::events] ERROR: error processing event: failed to resolve project information


  caused by: failed to fetch project state from upstream


2020-06-07T17:26:08Z [relay_server::actors::project_upstream] ERROR: error fetching project states: attempted to send request while not yet authenticated
```

Web log say:
```

17:22:40 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.


17:22:44 [INFO] sentry.plugins.github: apps-not-configured


*** Starting uWSGI 2.0.18 (64bit) on [Sun Jun  7 17:22:44 2020] ***


compiled with version: 8.3.0 on 02 June 2020 12:16:11


os: Linux-5.4.41-1-pve #1 SMP PVE 5.4.41-1 (Fri, 15 May 2020 15:06:08 +0200)


nodename: 1d92eb62d64a


machine: x86_64


clock source: unix


detected number of CPU cores: 8


current working directory: /


detected binary path: /usr/local/bin/uwsgi


!!! no internal routing support, rebuild with pcre support !!!


your processes number limit is 63318


your memory page size is 4096 bytes


detected max file descriptor number: 524288


lock engine: pthread robust mutexes


thunder lock: enabled


uWSGI http bound on 0.0.0.0:9000 fd 6


uwsgi socket 0 bound to TCP address 127.0.0.1:45899 (port auto-assigned) fd 3


Python version: 2.7.16 (default, Oct 17 2019, 07:39:30)  [GCC 8.3.0]


Set PythonHome to /usr/local


Python main interpreter initialized at 0x55ac8559f030


python threads support enabled


your server socket listen backlog is limited to 100 connections


your mercy for graceful operations on workers is 60 seconds


setting request body buffering size to 65536 bytes


mapped 543520 bytes (530 KB) for 2 cores


*** Operational MODE: threaded ***


spawned uWSGI master process (pid: 19)


spawned uWSGI worker 1 (pid: 23, cores: 2)


spawned uWSGI http 1 (pid: 24)


17:22:45 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.


17:22:49 [INFO] sentry.plugins.github: apps-not-configured


WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x55ac8559f030 pid: 23 (default app)


172.21.0.17 - - [07/Jun/2020:17:22:49 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"


172.21.0.24 - - [07/Jun/2020:17:22:53 +0000] "GET /api/0/organizations/iobroker/broadcasts/ HTTP/1.1" 200 1017 "https://sentry.iobroker.net/organizations/iobroker/events/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"


172.21.0.24 - - [07/Jun/2020:17:22:54 +0000] "GET /api/0/organizations/iobroker/projects/?per_page=50 HTTP/1.1" 200 33216 "https://sentry.iobroker.net/organizations/iobroker/events/?project=73" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"


172.21.0.24 - - [07/Jun/2020:17:22:54 +0000] "GET /api/0/organizations/iobroker/tags/?statsPeriod=14d&use_cache=1&project=13 HTTP/1.1" 200 1574 "https://sentry.iobroker.net/organizations/iobroker/events/?project=73" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"


172.21.0.24 - - [07/Jun/2020:17:22:54 +0000] "GET /api/0/organizations/iobroker/tags/?statsPeriod=14d&use_cache=1&project=73 HTTP/1.1" 200 1590 "https://sentry.iobroker.net/organizations/iobroker/events/?project=73" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"


172.21.0.24 - - [07/Jun/2020:17:22:54 +0000] "GET /api/0/organizations/iobroker/releases/?project=73 HTTP/1.1" 200 2605 "https://sentry.iobroker.net/organizations/iobroker/events/?project=73" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"


172.21.0.17 - - [07/Jun/2020:17:22:55 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"


172.21.0.24 - - [07/Jun/2020:17:22:55 +0000] "GET /api/0/organizations/iobroker/events-stats/?interval=30m&project=73&query=&statsPeriod=28d HTTP/1.1" 200 37828 "https://sentry.iobroker.net/organizations/iobroker/events/?project=73" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"


172.21.0.24 - - [07/Jun/2020:17:22:54 +0000] "GET /api/0/organizations/iobroker/events/?statsPeriod=14d&project=73 HTTP/1.1" 200 97972 "https://sentry.iobroker.net/organizations/iobroker/events/?project=73" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"


172.21.0.24 - - [07/Jun/2020:17:22:56 +0000] "GET /_static/1590854662/sentry/dist/nodejs.1910c5.svg HTTP/1.1" 200 589 "https://sentry.iobroker.net/organizations/iobroker/events/?project=73" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0"


172.21.0.17 - - [07/Jun/2020:17:23:02 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"


172.21.0.17 - - [07/Jun/2020:17:23:14 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"


172.21.0.17 - - [07/Jun/2020:17:23:31 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"


172.21.0.17 - - [07/Jun/2020:17:23:56 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"


172.21.0.17 - - [07/Jun/2020:17:24:35 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"


172.21.0.17 - - [07/Jun/2020:17:25:33 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"


172.21.0.17 - - [07/Jun/2020:17:26:33 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 663 "-" "actix-web/0.7.19"
```

Ingest Log
```
17:22:41 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.


17:22:45 [INFO] sentry.plugins.github: apps-not-configured


%3|1591550565.292|FAIL|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.10:9092 failed: Connection refused


%3|1591550565.292|ERROR|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.21.0.10:9092 failed: Connection refused


%3|1591550565.292|ERROR|rdkafka#consumer-1| [thrd:kafka:9092/bootstrap]: 1/1 brokers are down


17:22:51 [INFO] batching-kafka-consumer: New partitions assigned: [TopicPartition{topic=ingest-attachments,partition=0,offset=-1001,error=None}, TopicPartition{topic=ingest-events,partition=0,offset=-1001,error=None}, TopicPartition{topic=ingest-transactions,partition=0,offset=-1001,error=None}]
```

And in fact the same result ... no new events ... So I changed back to removing nginx and relay again :-(

I hope the logs help

**Comment by synkc** [comment] 2020-06-18 01:36
+1

**Comment by Apollon77** [comment] 2020-06-18 06:53
@synkc Better use "thumbs up" on the first post to show that you are also affected

**Comment by Apollon77** [comment] 2020-06-18 06:54
@BYK Were the logs helpful or do you need anything else?

**Comment by BYK** [comment] 2020-07-10 21:43
This was a duplicate of #486 and was closed by #576.

@Apollon77 - sorry for the very late reply. The logs indeed helped me pinpoint the issue, I just forgot to respond here.

Hope the new fix works for you too.

**Closed by BYK** 2020-07-10 21:43 UTC
Labels: needs-info

**Comment by Apollon77** [comment] 2020-07-10 21:45
Will try the next days. Thank you!

**Comment by Apollon77** [comment] 2020-07-27 11:44
@BYK Ok worked now, BUT I needed to add your changes manually to my "sentry.config.py" (and I saw that there are many other changes I do not have in mine ... is this a problem?) ... and I just saw them because I checked your PR ... for other users this is very intransparent.
Yoiu should maybe this about a better way for that config vs "defaults"

**Comment by BYK** [comment] 2020-08-03 19:58
@Apollon77 - valid complaint. We are aware of the non-obvious need to update your configuration files on updates and hoping to find a satisfactory solution to this in the near future.
