### ISSUE TITLE
Alerts menu is missing in the main sentry on-premise installation web page

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [getsentry/onpremise#668] opened 2020-09-09 09:56 UTC
## Version Information

Version: Sentry 20.8.017e488c

## Description

The `Alerts` menu is not available however it is present in the cloud version at sentry.io. Is this a limitation of the on-premise version? I struggled to find any docs that would provide the functionality matrix to compare the features available in the on-premise version to the features one get with a paid plan such as Team or Business.

When attempting to access the web page http://127.0.0.1:9000/organizations/sentry/alerts/?project=1, a message is shown `You don't have access to this feature`

![Screenshot 2020-09-09 at 10 52 15](https://user-images.githubusercontent.com/59651540/92583730-aff99700-f28a-11ea-8a62-64dca51b432a.png)

The sentry.io menu:

![Screenshot 2020-09-09 at 10 55 05](https://user-images.githubusercontent.com/59651540/92583938-f2bb6f00-f28a-11ea-8dd8-4a5e96e39179.png)

**Comment by BYK** [comment] 2020-09-09 19:32
This feature is not yet available to self-hosted until we make add the necessary infrastructure bits.

**Comment by BYK** [comment] 2020-09-09 19:47
Correction, "metric alerts" feature is not yet available. That said you should be seeing this on the sidebar. This is a configuration issue on our side and we'll fix it.

Thanks a lot for bringing this up!

**Comment by alexey-tereshenkov-oxb** [comment] 2020-09-10 08:24
Lovely, many thanks for looking into this! Is it in general true that functionality available on sentry.io for a paid plan say Team or Business should be available in the on-premise version? Or is there any feature(s) that you don't intentionally make available in the free self-hosted version to encourage using a paid cloud version at sentry.io? Thanks!

**Comment by BYK** [comment] 2020-09-11 10:21
https://sentry.io/_/open-source/
>We pride ourselves on delivering a unified, free, open-source service, where our cloud offering has the same functionality as our open-source offering. This stands in contrast to other open-source companies, who offer a reduced “open core” feature set that moves critical features into a paid, closed-source version of the software.

Guess that answers your question 😉

**Comment by alexey-tereshenkov-oxb** [comment] 2020-09-11 10:37
@BYK amazing, thank you. Looking forward to having the Alerts tab visible in some of the future versions of sentry on-premise. Thanks again for the support!

**Comment by BYK** [comment] 2020-09-11 11:05
@alexey-tereshenkov-oxb - we are aiming to get the tab on the next release (Sep 15) but specifically Metric Alerts needs to wait at least until the next release. Thanks again for bringing this up!

**Comment by alexey-tereshenkov-oxb** [comment] 2020-09-11 11:13
> @alexey-tereshenkov-oxb - we are aiming to get the tab on the next release (Sep 15) but specifically Metric Alerts needs to wait at least until the next release. Thanks again for bringing this up!

No rush at all!

**Comment by BYK** [comment] 2020-09-11 12:54
@alexey-tereshenkov-oxb just heard back from the team and turns out this is not a bug 😁 It was just enabled after `20.8.0` was released. So it should be available on the nightly builds and will be available automatically with the next release, hence closing the issue.

**Closed by BYK** 2020-09-11 12:54 UTC
Labels: bug
