### ISSUE TITLE
Receiving/Sending events fails

### ISSUE THREAD

**Issue by repomaa** [getsentry/onpremise#383] opened 2020-02-07 11:15 UTC
I migrated from 9.1.2 and cannot receive events since. Not even with the 'send sample event' button.

Kafka shows a lot of errors like these:
```
[2020-02-07 10:47:27,429] ERROR [Controller id=1004 epoch=12] Controller 1004 epoch 12 failed to change state for partition __consumer_offsets-40 from OfflinePartition to OnlinePartition (state.change.logger)
kafka.common.StateChangeFailedException: Failed to elect leader for partition __consumer_offsets-40 under strategy OfflinePartitionLeaderElectionStrategy
        at kafka.controller.PartitionStateMachine$$anonfun$doElectLeaderForPartitions$3.apply(PartitionStateMachine.scala:366)
        at kafka.controller.PartitionStateMachine$$anonfun$doElectLeaderForPartitions$3.apply(PartitionStateMachine.scala:364)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at kafka.controller.PartitionStateMachine.doElectLeaderForPartitions(PartitionStateMachine.scala:364)
        at kafka.controller.PartitionStateMachine.electLeaderForPartitions(PartitionStateMachine.scala:292)
        at kafka.controller.PartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:210)
        at kafka.controller.PartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:133)
        at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:123)
        at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:109)
        at kafka.controller.PartitionStateMachine.startup(PartitionStateMachine.scala:66)
        at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:260)
        at kafka.controller.KafkaController.kafka$controller$KafkaController$$elect(KafkaController.scala:1221)
        at kafka.controller.KafkaController$Startup$.process(KafkaController.scala:1134)
        at kafka.controller.ControllerEventManager$ControllerEventThread$$anonfun$doWork$1.apply$mcV$sp(ControllerEventManager.scala:89)
        at kafka.controller.ControllerEventManager$ControllerEventThread$$anonfun$doWork$1.apply(ControllerEventManager.scala:89)
        at kafka.controller.ControllerEventManager$ControllerEventThread$$anonfun$doWork$1.apply(ControllerEventManager.scala:89)
        at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
        at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:88)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:82)
```

**Comment by McSneaky** [comment] 2020-02-26 09:52
Got exactly the same error after updating from 10.x.x to latest 10.x.x

**Comment by Kampfmoehre** [comment] 2020-03-11 11:58
I have the same problem, after trying to deploy Sentry to Kubernetes.

**Comment by BYK** [comment] 2020-03-11 16:58
This seems like a network partition issue: https://stackoverflow.com/questions/53677435/kafka-failed-to-change-state-for-partition-from-onlinepartition-to-onlinepartiti

Since we only have 1 Kafka instance in this repo, I'm going to close this as you should never have this issue with a single instance so I'm assuming this is all k8s stuff.

If not, I'm willing to reopen and investigate with detailed steps for reproduction.

**Closed by BYK** 2020-03-11 16:58 UTC

**Comment by Kampfmoehre** [comment] 2020-03-12 07:12
We have only one instance of Kafka running.

The error message in the linked Stackoverflow question is slightly different than ours, it reads `from OfflinePartition to OnlinePartition` and also we have also other connection related errors:
```
ERROR [Controller id=1004 epoch=6] Controller 1004 epoch 6 failed to change state for partition __consumer_offsets-40 from OfflinePartition to OnlinePartition (state.change.logger)
kafka.common.StateChangeFailedException: Failed to elect leader for partition __consumer_offsets-40 under strategy OfflinePartitionLeaderElectionStrategy(false)
at kafka.controller.ZkPartitionStateMachine.$anonfun$doElectLeaderForPartitions$7(PartitionStateMachine.scala:427)
at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
at kafka.controller.ZkPartitionStateMachine.doElectLeaderForPartitions(PartitionStateMachine.scala:424)
at kafka.controller.ZkPartitionStateMachine.electLeaderForPartitions(PartitionStateMachine.scala:335)
at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:236)
at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:157)
at kafka.controller.PartitionStateMachine.triggerOnlineStateChangeForPartitions(PartitionStateMachine.scala:73)
at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:58)
at kafka.controller.PartitionStateMachine.startup(PartitionStateMachine.scala:41)
at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:306)
at kafka.controller.KafkaController.elect(KafkaController.scala:1399)
at kafka.controller.KafkaController.processStartup(KafkaController.scala:1286)
at kafka.controller.KafkaController.process(KafkaController.scala:1908)
at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:53)
at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:137)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:137)
at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)

WARN [RequestSendThread controllerId=1004] Controller 1004's connection to broker kafka-confluent:9092 (id: 1004 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
java.net.SocketTimeoutException: Failed to connect within 30000 ms
at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:297)
at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:250)
at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)

WARN Client session timed out, have not heard from server in 4000ms for sessionid 0x100bf126e7c0004 (org.apache.zookeeper.ClientCnxn)
```

What I don't understand, we does the connection to itself fail? What we can we change to resolve this?

If it helps, here are the used ENV variables for the Kafka pod:
```yaml
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper
        - name: KAFKA_PORT_NUMBER
          value: "9092"
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:$(KAFKA_PORT_NUMBER)
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://$(MY_POD_NAME).kafka-confluent-headless.sentry.svc.cluster.local:$(KAFKA_PORT_NUMBER)
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_BROKER_ID
          value: "-1"
        - name: KAFKA_CFG_DELETE_TOPIC_ENABLE
          value: "false"
        - name: KAFKA_HEAP_OPTS
          value: -Xmx1024m -Xms1024m
        - name: KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES
          value: "10000"
        - name: KAFKA_CFG_LOG_FLUSH_INTERVAL_MS
          value: "1000"
        - name: KAFKA_CFG_LOG_RETENTION_BYTES
          value: "1073741824"
        - name: KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS
          value: "300000"
        - name: KAFKA_CFG_LOG_RETENTION_HOURS
          value: "168"
        - name: KAFKA_CFG_MESSAGE_MAX_BYTES
          value: "1000012"
        - name: KAFKA_CFG_LOG_SEGMENT_BYTES
          value: "1073741824"
        - name: KAFKA_CFG_LOG_DIRS
          value: /bitnami/kafka/data
        - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
          value: https
        - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_CFG_NUM_IO_THREADS
          value: "8"
        - name: KAFKA_CFG_NUM_NETWORK_THREADS
          value: "3"
        - name: KAFKA_CFG_NUM_PARTITIONS
          value: "1"
        - name: KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR
          value: "1"
        - name: KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES
          value: "102400"
        - name: KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES
          value: "104857600"
        - name: KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES
          value: "102400"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "6000"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-confluent:9092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: CONFLUENT_SUPPORT_METRICS_ENABLE
          value: "false"
        - name: KAFKA_LOG4J_LOGGERS
          value: kafka.cluster=WARN,kafka.controller=WARN,kafka.coordinator=WARN,kafka.log=WARN,kafka.server=WARN,kafka.zookeeper=WARN,state.change.logger=WARN
        - name: KAFKA_LOG4J_ROOT_LOGLEVEL
          value: WARN
        - name: KAFKA_TOOLS_LOG4J_LOGLEVEL
          value: WARN
```

If there is anything more I can provide to help with this, please let me know.

**Comment by McSneaky** [comment] 2020-03-12 08:58
Got it on single VPS when just following upgrade guide. Using exactly the same `docker-compose` file as given in repo. For me the error is exactly the same as original issue

**Comment by BYK** [comment] 2020-03-12 11:24
@Kampfmoehre - it may have something to do with Zookeeper persistence. Sounds like some data is corrupt to me but I am no Kafka expert. I recommend asking around over at StackOverflow or [our forums](https://forum.sentry.io) to get help from more experienced Kafka people.

@McSneaky - if you think this is due to a configuration issue in this repo, please file a new issue with the full install/upgrade logs along with Kafka and Zookeeper logs. That said my suspicion is whatever you are experiencing is due to some ungraceful shutdown or volume persistence issues.

**Comment by McSneaky** [comment] 2020-03-12 13:57
I'm thinking it's about those two last too (ungraceful shutdown or volume persistence issues), since I weren't able to reproduce it on second VPS, which went thro same upgrade process.
Digging deeper into Kafka too, meanwhile hoping that someone, who happens to have a solution will stumble to here :slightly_smiling_face:

**Comment by ityoung** [comment] 2020-05-27 01:12
I met that error on k8s, and resolved after I recreate all PVC an Deployment.

**Comment by AkshayNarayan777** [comment] 2020-05-27 06:16
Im facing this issue currently.  Controller 1004 epoch 53 failed to change state for partition __consumer_offsets-30 from OfflinePartition to OnlinePartition (state.change.logger)

**Comment by McSneaky** [comment] 2020-05-27 09:22
I think it would be solved with it: https://github.com/getsentry/onpremise/issues/502
