### ISSUE TITLE
Can't install on Ubuntu 20.04 LTS due to docker-compose version

### ISSUE THREAD

**Issue by arctica** [getsentry/onpremise#1062] opened 2021-08-16 19:02 UTC
### Version

21.8.0

### Steps to Reproduce

Tried to upgrade from 20.12.1 to 21.8.0 but the install.sh script fails when checking the minimum docker-compose version and drops the -h output into the console.

Checking the source of install/check-minimum-requirements.sh seems to indicate that Sentry requires version 1.28 but Ubuntu only provides 1.25 (even in latest non-LTS releases). See https://packages.ubuntu.com/focal/docker-compose

This change seems to have been introduced recently as 21.7 still required docker-compose 1.24.1

### Expected Result

Able to upgrade/install Sentry on Ubuntu 20.04 LTS

### Actual Result

root@sentry:~/onpremise-21.8.0# ./install.sh
▶ Parsing command line ...

▶ Setting up error handling ...

▶ Checking minimum requirements ...
Define and run multi-container applications with Docker.

Usage:
  docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
  docker-compose -h|--help

Options:
  -f, --file FILE             Specify an alternate compose file
                              (default: docker-compose.yml)
  -p, --project-name NAME     Specify an alternate project name
                              (default: directory name)
  --verbose                   Show more output
  --log-level LEVEL           Set log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  --no-ansi                   Do not print ANSI control characters
  -v, --version               Print version and exit
  -H, --host HOST             Daemon socket to connect to

  --tls                       Use TLS; implied by --tlsverify
  --tlscacert CA_PATH         Trust certs signed only by this CA
  --tlscert CLIENT_CERT_PATH  Path to TLS certificate file
  --tlskey TLS_KEY_PATH       Path to TLS key file
  --tlsverify                 Use TLS and verify the remote
  --skip-hostname-check       Don't check the daemon's hostname against the
                              name specified in the client certificate
  --project-directory PATH    Specify an alternate working directory
                              (default: the path of the Compose file)
  --compatibility             If set, Compose will attempt to convert keys
                              in v3 files to their non-Swarm equivalent
  --env-file PATH             Specify an alternate environment file

Commands:
  build              Build or rebuild services
  bundle             Generate a Docker bundle from the Compose file
  config             Validate and view the Compose file
  create             Create services
  down               Stop and remove containers, networks, images, and volumes
  events             Receive real time events from containers
  exec               Execute a command in a running container
  help               Get help on a command
  images             List images
  kill               Kill containers
  logs               View output from containers
  pause              Pause services
  port               Print the public port for a port binding
  ps                 List containers
  pull               Pull service images
  push               Push service images
  restart            Restart services
  rm                 Remove stopped containers
  run                Run a one-off command
  scale              Set number of containers for a service
  start              Start services
  stop               Stop services
  top                Display the running processes
  unpause            Unpause services
  up                 Create and start containers
  version            Show the Docker-Compose version information
An error occurred, caught SIGERR on line 11
Cleaning up...

**Comment by MenschenToaster** [comment] 2021-08-16 19:38
Reinstall docker-compose with this: https://docs.docker.com/compose/install/
Just execute the commands under the linux section, it will overwrite the old compose

**Comment by MenschenToaster** [comment] 2021-08-16 19:51
If it still doesn't work with another error update docker too

**Comment by arctica** [comment] 2021-08-16 20:19
@MenschenToaster installing the newer docker-compose binary as in your link did make the install.sh pass that part but at the end it failed saying I skipped some hard-stop which shouldn't be the case according to the official docs. I upgraded then step by step to 21.5 then 21.6.3, then 21.7 and finally after that it let me upgrade to 21.8. Even from 21.6.3 it didn't want to upgrade to 21.7.

Well, all is good now. Thanks for your suggestion, much appreciated.

I'm not sure if the issue should be closed as maybe it would be a good idea to mention in the install docs that docker-compose from the Ubuntu repos won't suffice. Also the version check seems to not work properly as it just fails with unrecognized cli params.

**Comment by frame** [comment] 2021-08-16 20:36
> I upgraded then step by step to 21.5 then 21.6.3, then 21.7 and finally after that it let me upgrade to 21.8. Even from 21.6.3 it didn't want to upgrade to 21.7.

This isn't strictly related this this specific update only. The docs mention that we should perform all version upgrades individually. See https://develop.sentry.dev/self-hosted/releases/#upgrading

**Comment by arctica** [comment] 2021-08-16 20:41
> This isn't strictly related this this specific update only. The docs mention that we should perform all version upgrades individually. See https://develop.sentry.dev/self-hosted/releases/#upgrading

That page indeed recommends that but by reading the following page one gets the impression that it should not be necessary: https://develop.sentry.dev/self-hosted/#upgrading Espacially this part:

> If you are coming from an intermediate version such as 20.5.0, you can directly go to latest:

**Comment by chadwhitacre** [comment] 2021-08-16 23:33
Thanks for the reports, all. Sorry for the trouble. 😕 Looks like we have [a workaround](https://github.com/getsentry/onpremise/issues/1062#issuecomment-899768741), at least. 👍

Ftr, #1051 is where we bumped the minimum `docker-compose` version from `1.24.1` to `1.28.0`.

@BYK What do you think? Should we drop back to an older `docker-compose` version, or treat this as expected behavior, perhaps further documenting the change as @arctica [suggests](https://github.com/getsentry/onpremise/issues/1062#issuecomment-899793205)?

If we want to get complicated we could branch under `install.sh` based on which `docker-compose` version is being used, using `--ansi never` for newer versions and `--no-ansi` for older versions. PR at #1063 if we want to go this route.

**Comment by chadwhitacre** [comment] 2021-08-16 23:35
> Ftr, #1051 is where we bumped the minimum docker-compose version from `1.24.1` to `1.28.0`.

Not to be confused with #1050, where we bumped the version of `docker-compose` we use in tests. Hmm ... do we want to parameterize that in testing, test multiple docker-compose versions? Especially if we go with #1063 ... 🤔

**Comment by BYK** [comment] 2021-08-17 12:45
@chadwhitacre we cannot go back to an older `docker-compose` version as the main reason for upgrade was the support for new health check instructions and the new `depends_on` syntax that supports "service healthy" status.

My takeaways from this thread are:

1. We should fix the `docker-compose` version check to be backwards-compatible
2. We should clarify our docs regarding the upgrade requirements

Will be addressing those.

**Comment by BYK** [comment] 2021-08-18 20:51
Closing the issue as we completed all follow-up actions we identified.

Thanks a lot for the report again and feel free to ping us back if you see any further issues please.

**Closed by BYK** 2021-08-18 20:51 UTC
Labels: Status: In Progress
