### ISSUE TITLE
url-prefix missing from the config.yml

### ISSUE THREAD

**Issue by sdwerwed** [getsentry/onpremise#560] opened 2020-07-01 18:07 UTC
Hello, I modied the [nginx.conf](https://github.com/getsentry/onpremise/blob/master/nginx/nginx.conf) to support ssl and it is working **but** XML https:hostname/saml/metadata/sentry/ is hardcoded. It has the http instead of https, also port is 9000 instead of 443. The Url that people use is https://hostname:443, XML should contain this scheme otherwise Azure SSO can not connect to http url. I am using those settings:

**sentry.conf.py:**
```
###########
# SSL/TLS #
###########

# If you're using a reverse SSL proxy, you should enable the X-Forwarded-Proto
# header and enable the settings below

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

# End of SSL/TLS settings
```

**Nginx.conf:**

```

upstream relay {
        server relay:3000;
}

upstream sentry {
        server web:9000;
}

server {
        listen 443 ssl;
        server_name         xxxxxxxx.com;
        access_log          /var/log/nginx/access.log;
        error_log           /var/log/nginx/error.log;
        ssl_certificate     /etc/ssl/server2.crt;
        ssl_certificate_key /etc/ssl/server2.key;
        proxy_set_header X-Forwarded-Proto $scheme;
        location /api/store/ {
                proxy_pass http://relay;
        }
        location ~ ^/api/[1-9]\d*/ {
                proxy_pass http://relay;
        }
        location / {
                proxy_pass http://sentry;
        }
}
```

**Comment by sdwerwed** [comment] 2020-07-01 18:48
I made it work by adding a **new (or old)** key to the `./sentry/config.yml` `system.url-prefix: https://example.com`

**Comment by BYK** [comment] 2020-07-01 20:45
Hi, this config is not required as it is asked in the initial setup screen when Sentry detects this is a fresh installation. The value is recorded on the database and is used unless there's an override from the config files like you did.

Closing as this is not a bug.

**Closed by BYK** 2020-07-01 20:45 UTC

**Comment by littlehome-eugene** [comment] 2020-07-07 10:28
We have two Domain names associated with the machine, How can I change the hostname ?

**Comment by MaicolBen** [comment] 2020-07-10 15:51
> Hi, this config is not required as it is asked in the initial setup screen when Sentry detects this is a fresh installation

This still happens when you upgrade

**Comment by BYK** [comment] 2020-07-10 17:54
>This still happens when you upgrade

Yeah, when Sentry detects an upgrade, it shows the welcome screen again in case there are new settings you need to set.

**Comment by MaicolBen** [comment] 2020-07-10 17:58
It didn't happen to me, maybe related with https://github.com/getsentry/onpremise/issues/575 or something else
