### ISSUE TITLE
Error: Configuration file does not exist. Use 'sentry init' to initialize the file.

### ISSUE THREAD

**Issue by yuanzhian** [getsentry/onpremise#459] opened 2020-04-30 09:09 UTC

**Comment by dinesh-chander** [comment] 2020-04-30 11:07
Were you able to solve this?

**Comment by BYK** [comment] 2020-05-01 13:09
Duplicate of #449.

**Closed by BYK** 2020-05-01 13:09 UTC

**Comment by wuaixiaoyao** [comment] 2020-05-22 13:42
I also append in this problem
