### ISSUE TITLE
Backup/restore seems to not initialize Postgres sequences properly, resulting in UniqueViolation

### ISSUE THREAD

**Issue by e2-robert** [getsentry/onpremise#867] opened 2021-02-19 17:09 UTC
### Version Information

Version: *20.9.0*

### Steps to Reproduce

Have at least one API token set up.

1.Backup: `docker-compose run --rm -T -e SENTRY_LOG_LEVEL=CRITICAL web export > sentry/backup.json`
2. Replace `u'` with `\"` to workaround #866
3. Restore: `docker-compose run --rm -T web import /etc/sentry/backup.json`

### Expected Result

API keys get restored. Adding new ones will work fine

### Actual Result

API keys got restored, however adding a new one failed with a 500 status code.

Logs read: `IntegrityError: UniqueViolation('duplicate key value violates unique constraint "sentry_apitoken_pkey"\nDETAIL:  Key (id)=(5) already exists.\n',)`

Since I got 5 API keys restored, I needed to re-press the create button 6 times, until last request went through - you can see a 200 status code in below's log.

### Logs

```
web_1                          | SQL: INSERT INTO "sentry_apitoken" ("scopes", "scope_list", "application_id", "user_id", "token", "refresh_token", "expires_at", "date_added") VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING "sentry_apitoken"."id"
web_1                          | 16:53:03 [ERROR] sentry_sdk.errors: Unexpected status code: 502 (body: <html>
web_1                          | <head><title>502 Bad Gateway</title></head>
web_1                          | <body>
web_1                          | <center><h1>502 Bad Gateway</h1></center>
web_1                          | <hr><center>nginx</center>
web_1                          | </body>
web_1                          | </html>
web_1                          | )
web_1                          | 16:53:06 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://127.0.0.1/api/0/api-tokens/' method=u'POST' ip_address=u'10.17.12.1')
web_1                          | Traceback (most recent call last):
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 134, in handle_exception
web_1                          |     response = super(Endpoint, self).handle_exception(exc)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
web_1                          |     self.raise_uncaught_exception(exc)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 247, in dispatch
web_1                          |     response = handler(request, *args, **kwargs)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/api_tokens.py", line 39, in post
web_1                          |     user=request.user, scope_list=result["scopes"], refresh_token=None, expires_at=None
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
web_1                          |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
web_1                          |     obj.save(force_insert=True, using=self.db)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
web_1                          |     force_update=force_update, update_fields=update_fields)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
web_1                          |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
web_1                          |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
web_1                          |     using=using, raw=raw)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
web_1                          |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1079, in _insert
web_1                          |     return query.get_compiler(using=using).execute_sql(return_id)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
web_1                          |     cursor.execute(sql, params)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 489, in execute
web_1                          |     return real_execute(self, sql, params)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
web_1                          |     return self.cursor.execute(sql, params)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
web_1                          |     six.reraise(dj_exc_type, dj_exc_value, traceback)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
web_1                          |     return self.cursor.execute(sql, params)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 81, in inner
web_1                          |     raise_the_exception(self.db, e)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 79, in inner
web_1                          |     return func(self, *args, **kwargs)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
web_1                          |     return func(self, *args, **kwargs)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 99, in inner
web_1                          |     six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
web_1                          |     return func(self, sql, *args, **kwargs)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 78, in execute
web_1                          |     return self.cursor.execute(sql, clean_bad_params(params))
web_1                          | IntegrityError: UniqueViolation('duplicate key value violates unique constraint "sentry_apitoken_pkey"\nDETAIL:  Key (id)=(4) already exists.\n',)
web_1                          | SQL: INSERT INTO "sentry_apitoken" ("scopes", "scope_list", "application_id", "user_id", "token", "refresh_token", "expires_at", "date_added") VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING "sentry_apitoken"."id"
web_1                          | 16:53:06 [ERROR] sentry_sdk.errors: Unexpected status code: 502 (body: <html>
web_1                          | <head><title>502 Bad Gateway</title></head>
web_1                          | <body>
web_1                          | <center><h1>502 Bad Gateway</h1></center>
web_1                          | <hr><center>nginx</center>
web_1                          | </body>
web_1                          | </html>
web_1                          | )
web_1                          | 16:53:30 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://127.0.0.1/api/0/api-tokens/' method=u'POST' ip_address=u'10.17.12.1')
postgres_1                     | ERROR:  duplicate key value violates unique constraint "sentry_apitoken_pkey"
postgres_1                     | DETAIL:  Key (id)=(5) already exists.
postgres_1                     | STATEMENT:  INSERT INTO "sentry_apitoken" ("scopes", "scope_list", "application_id", "user_id", "token", "refresh_token", "expires_at", "date_added") VALUES (0, ARRAY['event:read','project:read','project:write','event:write','project:admin','event:admin'], NULL, 1, '8609a5ed2d204064b2fe03e046520b48583dc3ffdd24421296fbdf612ea97b26', NULL, NULL, '2021-02-19T16:53:30.074339+00:00'::timestamptz) RETURNING "sentry_apitoken"."id"
web_1                          | Traceback (most recent call last):
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 134, in handle_exception
web_1                          |     response = super(Endpoint, self).handle_exception(exc)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
web_1                          |     self.raise_uncaught_exception(exc)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 247, in dispatch
web_1                          |     response = handler(request, *args, **kwargs)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/api_tokens.py", line 39, in post
web_1                          |     user=request.user, scope_list=result["scopes"], refresh_token=None, expires_at=None
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
web_1                          |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
web_1                          |     obj.save(force_insert=True, using=self.db)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
web_1                          |     force_update=force_update, update_fields=update_fields)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
web_1                          |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
web_1                          |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
web_1                          |     using=using, raw=raw)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
web_1                          |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1079, in _insert
web_1                          |     return query.get_compiler(using=using).execute_sql(return_id)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
web_1                          |     cursor.execute(sql, params)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 489, in execute
web_1                          |     return real_execute(self, sql, params)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
web_1                          |     return self.cursor.execute(sql, params)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
web_1                          |     six.reraise(dj_exc_type, dj_exc_value, traceback)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
web_1                          |     return self.cursor.execute(sql, params)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 81, in inner
web_1                          |     raise_the_exception(self.db, e)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 79, in inner
web_1                          |     return func(self, *args, **kwargs)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
web_1                          |     return func(self, *args, **kwargs)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 99, in inner
web_1                          |     six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
web_1                          |     return func(self, sql, *args, **kwargs)
web_1                          |   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 78, in execute
web_1                          |     return self.cursor.execute(sql, clean_bad_params(params))
web_1                          | IntegrityError: UniqueViolation('duplicate key value violates unique constraint "sentry_apitoken_pkey"\nDETAIL:  Key (id)=(5) already exists.\n',)
web_1                          | SQL: INSERT INTO "sentry_apitoken" ("scopes", "scope_list", "application_id", "user_id", "token", "refresh_token", "expires_at", "date_added") VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING "sentry_apitoken"."id"
nginx_1                        | 10.17.12.1 - - [19/Feb/2021:16:53:30 +0000] "POST /api/0/api-tokens/ HTTP/1.1" 500 72 "http://127.0.0.1:9000/settings/account/api/auth-tokens/new-token/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0" "-"
web_1                          | 16:53:30 [ERROR] sentry_sdk.errors: Unexpected status code: 502 (body: <html>
web_1                          | <head><title>502 Bad Gateway</title></head>
web_1                          | <body>
web_1                          | <center><h1>502 Bad Gateway</h1></center>
web_1                          | <hr><center>nginx</center>
web_1                          | </body>
web_1                          | </html>
web_1                          | )
worker_1                       | 16:54:15 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
web_1                          | 16:54:45 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://127.0.0.1/api/0/api-tokens/' method=u'POST' ip_address=u'10.17.12.1')
web_1                          | 16:54:45 [INFO] sentry.security: user.api-token-generated (user_id=1 actor_id=1 ip_address=u'10.17.12.1')
web_1                          | 16:54:45 [INFO] sentry.mail: mail.queued (message_to=(u'robert.koch@e-2.at',) simplelazyobject_id=1 message_id=u'<20210219165445.24.52606@e-2.at>' message_type=u'api-token-generated')
nginx_1                        | 10.17.12.1 - - [19/Feb/2021:16:54:45 +0000] "POST /api/0/api-tokens/ HTTP/1.1" 201 297 "http://127.0.0.1:9000/settings/account/api/auth-tokens/new-token/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0" "-"
web_1                          | 16:54:46 [INFO] sentry.superuser: superuser.request (user_id=1 url=u'http://127.0.0.1/api/0/api-tokens/' method=u'GET' ip_address=u'10.17.12.1')
nginx_1                        | 10.17.12.1 - - [19/Feb/2021:16:54:46 +0000] "GET /api/0/api-tokens/ HTTP/1.1" 200 510 "http://127.0.0.1:9000/settings/account/api/auth-tokens/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0" "-"
```

**Comment by BYK** [comment] 2021-02-19 19:53
Duplicate of #3840, should be resolved with #23957.

**Closed by BYK** 2021-02-19 19:53 UTC
Labels: Status: Unrouted
