### ISSUE TITLE
After installation, all the existing docker images are disappeared

### ISSUE THREAD

**Issue by lovdin** [getsentry/onpremise#419] opened 2020-03-25 06:28 UTC
I have several docker images before installing sentry. After installation, all my existing images are disappeared. Is that normal?

Date: `2020-03-24`
OS: `macOS 10.13.6`
Docker: `19.03.8`
Docker-Compose: `1.25.4`
Sentry: `on-premise latest`

**Comment by BYK** [comment] 2020-04-20 14:47
Not really, that said it is very unlikely to be related to this repo nor possible to tell from what you have shared.

Closing as the issue is not applicable to this repo.

**Closed by BYK** 2020-04-20 14:47 UTC
