### ISSUE TITLE
on premise is not on premises

### ISSUE THREAD

**Issue by jensenbox** [getsentry/onpremise#1042] opened 2021-07-26 19:13 UTC
### Problem Statement

I totally get that this would be highly disruptive but you are not using proper English here.

The repository should be renamed to be `onpremises` not `onpremise`

- https://www.google.com/search?q=on+premise+vs+on+premises
- https://www.cloudelicious.net/when-grammar-is-becoming-a-challenge-on-premise-vs-on-premises/
- https://www.merriam-webster.com/dictionary/premises
- https://collectivecontent.co.uk/2018/04/19/should-i-say-on-premise-or-on-premises-it/
- https://andrewschoen.medium.com/software-people-of-the-world-stop-saying-on-premise-you-sound-dumb-56692dae871d
- https://www.govloop.com/on-premise-vs-on-premises-the-debate-and-resolution/

### Solution Brainstorm

I have no other solution for you other than renaming the repository.

**Comment by BYK** [comment] 2021-07-26 20:43
Sort of duplicate of #796 so closing in favor of that.

Aside, as much as we care about proper English, renames like these are way more disruptive than the value they bring so it is very unlikely that we'll rename this repo any time soon and most probably the new name wouldn't be `onpremises`.

**Closed by BYK** 2021-07-26 20:43 UTC
Labels: Status: Untriaged
