### ISSUE TITLE
Error on welcome screen

### ISSUE THREAD

**Issue by nvbln** [getsentry/onpremise#164] opened 2019-04-11 10:28 UTC
# Error when submitting info in welcome screen

When doing a clean install and logging in with a superuser account, you're presented with the welcome screen. However, when filling all the data in (correctly), I get the error that not everything has been filled in correctly. The Sentry logs show this:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 90, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 190, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/system_options.py", line 79, in put
    options.set(k, v)
  File "/usr/local/lib/python2.7/site-packages/sentry/options/manager.py", line 90, in set
    ), '%r cannot be changed at runtime because it is configured on disk' % key
AssertionError: u'mail.from' cannot be changed at runtime because it is configured on disk
```

I looked into it, and it's because it's also setting settings which have already been set, like the mail options. The data being sent is:

```
'{"mail.use-tls":true,"mail.username":"","mail.port":25,"system.admin-email":"joe@example.com","mail.password":"s","mail.from":"sentry@example.com,"system.url-prefix":"https://sentry.example.com,"auth.allow-registration":false,"mail.host":"mail.example.com","beacon.anonymous":true}'
```

which are already set to the correct values from the config (replaced with example ones). If you resent the same request without the mail data, you go immediately to the dashboard when logging in.

**Comment by gerald8** [comment] 2019-04-11 11:03
+1

**Comment by durnerj** [comment] 2019-04-11 11:38
+1

**Comment by dcramer** [comment] 2019-04-11 17:55
For reference, this is a duplicate of https://github.com/getsentry/docker-sentry/issues/163

**Comment by Suntgr** [comment] 2019-04-13 12:10
+1
http://localhost:9000/api/0/internal/options/?query=is:required
Status Code: 500 INTERNAL SERVER ERROR
{detail: "Internal Error", errorId: "b22178680f5440a4893bb49b0cffc79e"}
alert there was a error saving your changes
what is the error?

**Comment by 23233** [comment] 2019-04-13 15:05
@Suntgr  +1  me too!!!

**Comment by 15751165579** [comment] 2019-04-16 07:37
@Suntgr i have the same problem, have you solved it ?

**Comment by markotitel** [comment] 2019-04-16 10:38
This may occur if you do not have enough RAM also.
@dcramer referenced another issue possibly.
I've assembled quick script for setting up Sentry on premise.
@Suntgr try it out if you still haven't solved your issue.

https://gist.github.com/markotitel/2cbb40ed5a745f0cf3f8ce12395efc11

**Comment by gerald8** [comment] 2019-04-16 10:52
try previous version




            
            
                
                    
                            
                                
                            
                            
                                melowwx
                            
                    
                        
                            
                                    邮箱：melowwx@gmail.com
                            
                        
                
            
        


On 04/16/2019 15:37, descire wrote: @Suntgr i have the same problem, have you solved it ?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/getsentry/onpremise","title":"getsentry/onpremise","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/getsentry/onpremise"}},"updates":{"snippets":[{"icon":"PERSON","message":"@15751165579 in #164: @Suntgr i have the same problem, have you solved it ?"}],"action":{"name":"View Issue","url":"https://github.com/getsentry/onpremise/issues/164#issuecomment-483546913"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/getsentry/onpremise/issues/164#issuecomment-483546913",
"url": "https://github.com/getsentry/onpremise/issues/164#issuecomment-483546913",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by joginsky** [comment] 2019-04-19 11:30
@Suntgr I have the same issue

**Comment by joginsky** [comment] 2019-04-19 12:31
I found the solution for @Suntgr's issue.

I updated config files:

### config.yml
with:
```
system.url-prefix: '<root-url>'
system.admin-email: '<my-email>'
```
... and all mail.* settings

and
### sentry.conf.py
with only db and github settings settings

From my case I assume that overwriting `mail.*` and `system.*` settings in `sentry.conf.py` causes this error, but when I put them in `config.yml` file problem disappeared.

That's how I solved it.

**Comment by Suntgr** [comment] 2019-04-20 08:40
> @Suntgr i have the same problem, have you solved it ?

sorry, i cannot find the error

**Comment by Suntgr** [comment] 2019-04-20 08:43
> I found the solution for @Suntgr's issue.
> 
> I updated config files:
> 
> ### config.yml
> with:
> 
> ```
> system.url-prefix: '<root-url>'
> system.admin-email: '<my-email>'
> ```
> ... and all mail.* settings
> 
> and
> 
> ### sentry.conf.py
> with only db and github settings settings
> 
> From my case I assume that overwriting `mail.*` and `system.*` settings in `sentry.conf.py` causes this error, but when I put them in `config.yml` file problem disappeared.
> 
> That's how I solved it.

no works for me. could do you show me your config.yml and sentry.conf.py

**Comment by dcramer** [comment] 2019-04-22 21:15
https://github.com/docker-library/official-images/pull/5772

**Closed by dcramer** 2019-04-22 21:15 UTC
