### ISSUE TITLE
Unable to install with docker compose 2.0.0

### ISSUE THREAD

**Issue by multinerd** [getsentry/onpremise#1110] opened 2021-10-06 16:44 UTC
### Version

21.10.0.dev0

### Steps to Reproduce

1 Change docker to use `Docker Compose v2`

![image](https://user-images.githubusercontent.com/6367998/136247451-50725a7d-b655-4c7b-b17c-d32d791d9629.png)

2. Run ./install.sh

### Expected Result

Sentry should install

### Actual Result

Error is thrown

```
▶ Parsing command line ...

▶ Setting up error handling ...

▶ Checking minimum requirements ...
FAIL: Expected minimum docker-compose version to be 1.28.0 but found Docker Compose version v2.0.0

```

**Comment by chadwhitacre** [comment] 2021-10-06 16:57
I believe this is a dupe of #962, yes?

**Closed by chadwhitacre** 2021-10-06 16:57 UTC
Labels: Status: Untriaged
