### ISSUE TITLE
New On-Premise installation Relay Issues

### ISSUE THREAD

**Issue by Alydus** [getsentry/onpremise#473] opened 2020-05-05 20:46 UTC
Hi,

Please excuse me as I'm very new to working with docker, however I've been on this issue for two days now and I'm completely clueless how to go about debugging this issue; I've had to use cached version of the docs due to the ongoing redirect issue in #466 

I've tried reinstalling sentry with default configs, and this issue still occurs;

Running 'docker-compose logs -f relay':
https://pastebin.com/497ui4du

Restarting the relay w/ 'docker-compose stop relay' and 'docker-compose start relay' does not solve the issue, I've also tried rebooting our entire server.

I'm running Relay through a NGINX reverse proxy, with the same NGINX settings as in the documentation.

**Comment by BYK** [comment] 2020-05-06 15:12
Duplicate of #475. 

Hey, I know that this issue is earlier than #475 but I happened to respond there before so merging this into that. Can you try the remedy I proposed there?

**Comment by Alydus** [comment] 2020-05-06 15:28
Hey @BYK thanks for the reply, I've downgraded to running Sentry 9 via Snapcraft on Ubuntu 18 - however #475 looks identical to my issues, and I'd love to try your fix.

If I can see enough reason to risk installing Sentry 10 again using docker like this I'll let you know if this is working again.

Thanks a bunch!

**Comment by BYK** [comment] 2020-05-06 15:34
@Alydus - There are a lot of great reasons to use Sentry 10 but I understand the concerns. I assure you that we are doing our best to make on-premise Sentry a viable and easy-to use solution.

**Closed by BYK** 2020-05-06 15:34 UTC
