### ISSUE TITLE
relay cannot connect to web

### ISSUE THREAD

**Issue by agrevtcev** [getsentry/onpremise#785] opened 2020-12-27 17:18 UTC
Hi team!
I have some trouble running latest 20.12.1 release.
Everything seems to be okay, but relay can't connect to web because it says it can't resolve web. What i tried to check is to ping web from inside relay container - it resolves well.
Host system: Ubuntu 20.04.1 LTS amd64
Docker version: 20.10.1, build 831ebea

Br, Alexey

```
2020-12-27T16:43:03Z [actix_net::server::server] INFO: Starting server on 0.0.0.0:3000
2020-12-27T16:43:03Z [relay_server::actors::controller] INFO: relay server starting
2020-12-27T16:43:03Z [relay_server::actors::connector] INFO: metered connector started
2020-12-27T16:43:03Z [relay_server::actors::events] INFO: event manager started
2020-12-27T16:43:03Z [relay_server::actors::project_local] INFO: project local cache started
2020-12-27T16:43:03Z [relay_server::actors::project_upstream] INFO: project upstream cache started
2020-12-27T16:43:03Z [relay_server::actors::project_cache] INFO: project cache started
2020-12-27T16:43:03Z [relay_server::actors::relays] INFO: key cache started
2020-12-27T16:43:03Z [actix::actors::resolver] WARN: Can not create system dns resolver: io error
2020-12-27T16:43:03Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: could not send request using actix-web client
  caused by: Failed to connect to host: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
2020-12-27T16:43:03Z [relay_server::actors::upstream] DEBUG: scheduling authentication retry in 0 seconds
2020-12-27T16:43:03Z [relay_server::actors::upstream] INFO: registering with upstream (http://web:9000/)
2020-12-27T16:43:03Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: could not send request using actix-web client
  caused by: Failed to connect to host: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
2020-12-27T16:43:03Z [relay_server::actors::upstream] DEBUG: scheduling authentication retry in 1 seconds
2020-12-27T16:43:04Z [rdkafka::client] ERROR: librdkafka: FAIL [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.31.4.2:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2020-12-27T16:43:04Z [rdkafka::client] ERROR: librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): kafka:9092/bootstrap: Connect to ipv4#172.31.4.2:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2020-12-27T16:43:04Z [rdkafka::client] ERROR: librdkafka: FAIL [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Connect to ipv4#172.31.4.2:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2020-12-27T16:43:04Z [rdkafka::client] ERROR: librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): kafka:9092/bootstrap: Connect to ipv4#172.31.4.2:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
2020-12-27T16:43:04Z [relay_server::actors::upstream] INFO: registering with upstream (http://web:9000/)
2020-12-27T16:43:04Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: could not send request using actix-web client
  caused by: Failed to connect to host: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
2020-12-27T16:43:04Z [relay_server::actors::upstream] DEBUG: scheduling authentication retry in 1 seconds
2020-12-27T16:43:05Z [relay_server::actors::upstream] INFO: registering with upstream (http://web:9000/)
2020-12-27T16:43:05Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: could not send request using actix-web client
  caused by: Failed to connect to host: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
2020-12-27T16:43:05Z [relay_server::actors::upstream] DEBUG: scheduling authentication retry in 2 seconds
2020-12-27T16:43:08Z [relay_server::actors::upstream] INFO: registering with upstream (http://web:9000/)
2020-12-27T16:43:08Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
  caused by: could not send request using actix-web client
  caused by: Failed to connect to host: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
  caused by: Failed resolving hostname: no record found for name: web type: AAAA class: IN
2020-12-27T16:43:08Z [relay_server::actors::upstream] DEBUG: scheduling authentication retry in 3 seconds
```

**Comment by agrevtcev** [comment] 2020-12-27 20:32
Downgrading resolved issue.
`apt-get install -y --allow-downgrades docker-ce=5:19.03.14~3-0~ubuntu-focal docker-ce-cli=5:19.03.14~3-0~ubuntu-focal`
https://github.com/getsentry/onpremise/issues/771

**Comment by kohenkatz** [comment] 2020-12-30 15:40
@agrevtcev You should close this issue since it is a duplicate.

**Comment by BYK** [comment] 2021-01-04 11:12
Duplicate of #771

**Closed by BYK** 2021-01-04 11:12 UTC
