### ISSUE TITLE
django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known

### ISSUE THREAD

**Issue by lvxingchen111** [getsentry/onpremise#424] opened 2020-03-31 13:42 UTC
hello:

I got the following error when I tried to install onpremise

`
django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
`

My attempts to replace the following versions all failed with the same error

`  
docker -v
Docker version 19.03.8, build afacb8b

docker-compose -v
docker-compose version 1.21.0, build 5920eb0
`

`
docker -v
Docker version 18.06.3-ce, build d7080c1

docker-compose version 1.23.0
`

**Comment by zdenekhatak** [comment] 2020-04-01 18:54
Might be related to https://github.com/getsentry/onpremise/issues/417

**Comment by BYK** [comment] 2020-04-20 14:48
Duplicate of #417.

**Closed by BYK** 2020-04-20 14:48 UTC
