### ISSUE TITLE
I am not able to create new release on existing project, I am getting redis key error( Failed to release <Lock: u’releasecommits:1:XXXXX’> due to error: ResponseError(‘No lock at key exists at key: l:releasecommits:1:XXXXX’,)) 

### ISSUE THREAD

**Issue by BKS1989** [getsentry/onpremise#1035] opened 2021-07-19 14:15 UTC
### Environment

self-hosted (`onpremise` deployment)

### Version

20.10.1

### Steps to Reproduce

Configure Redis  LRU cache to automatically evict old data as you add new data

### Expected Result

ResponseError: No lock at key exists at key: l:releasecommits:1:XXXXX

### Actual Result

Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/sentry/utils/locking/lock.py", line 57, in release self.backend.release(self.key, self.routing_key) File "/usr/local/lib/python2.7/site-packages/sentry/utils/locking/backends/redis.py", line 55, in release delete_lock(client, (self.prefix_key(key),), (self.uuid,)) File "/usr/local/lib/python2.7/site-packages/sentry/utils/redis.py", line 288, in call_script return script[0](keys, args, client) File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 3745, in __call__ return client.evalsha(self.sha, len(keys), *args) File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2829, in evalsha return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args) File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command return old_execute_command(self, name, *args, **kwargs) File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 839, in execute_command return self.parse_response(conn, command_name, **options) File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 853, in parse_response response = connection.read_response() File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 718, in read_response raise response ResponseError: No lock at key exists at key: l:releasecommits:1:XXXXX 06:51:00 [WARNING] sentry.utils.locking.lock: Failed to release <Lock: u'releasecommits:1:XXXXX'> due to error: ResponseError('No lock at key exists at key: l:releasecommits:1:XXXXX',)

**Comment by chadwhitacre** [comment] 2021-07-19 16:18
> Configure Redis LRU cache to automatically evict old data as you add new data

It looks to me like you are removing data from Redis directly, which I would totally expect to break Sentry. Why do you expect it _not_ to break Sentry?

Why are you configuring Redis this way? What problem are you trying to solve?

**Comment by BKS1989** [comment] 2021-07-19 17:08
Is there any way to regenerate redis cache,  We have disabled redis LRU cache policy,

**Comment by chadwhitacre** [comment] 2021-07-19 18:38
Not sure, you could ask around on the [forum/discord](https://open.sentry.io/) to see if other self-hosters have any experience with that, or you could dig around in the [codebase](https://github.com/getsentry/sentry) to find an answer. One way or another this seems like an issue on your side and not a bug in Sentry itself. Closing.

P.S. I recently noticed a [`sentry cleanup`](https://github.com/getsentry/sentry/blob/8ee5de900c7494e4e2c327aba7e97c9a63e5f5d0/src/sentry/runner/commands/cleanup.py) CLI command that maybe would help with what I'm guessing you were trying to do. Something to look into?

Good luck!

**Closed by chadwhitacre** 2021-07-19 18:38 UTC
Labels: Status: Needs More Information

**Comment by gaurav5430** [comment] 2021-07-19 19:58
> > Configure Redis LRU cache to automatically evict old data as you add new data
> 
> It looks to me like you are removing data from Redis directly, which I would totally expect to break Sentry. Why do you expect it _not_ to break Sentry?
> 
> Why are you configuring Redis this way? What problem are you trying to solve?

more info:

This started happening automatically with our sentry instance, where suddenly we could not create releases through the CI. We triaged to figure out that this is possibly happening because of the LRU cache policy on redis. 

The steps to reproduce mentioned here are an easy way to reproduce what (we suspect) is happening. We are NOT trying to do anything manually with the sentry installation. 

The question is: if this happened automatically, and if our understanding is correct that it is happening because of redis evicting keys, is there a way to re-initialize those keys? would a Sentry restart fix this for example? Any other info we can get, to see if we can somehow figure out why this happened or what is the fix , or where to look in the codebase?

FYI, the releases thing is working fine for any new project that we create.

**Comment by chadwhitacre** [comment] 2021-07-20 14:18
Found this in [the Redis docs](https://docs.redislabs.com/latest/rs/administering/database-operations/eviction-policy/):

> The eviction policy defines the methodology that Redis Enterprise Software uses when the database exceeds the memory limit.

Sounds like you're up against the limits of what `onpremise` is designed to handle, which is small workloads and proofs-of-concept. If you're not comfortable scaling Sentry on your own then our recommendation is to [migrate to SaaS](https://docs.sentry.io/product/sentry-basics/guides/migration/).

**Comment by gaurav5430** [comment] 2021-07-20 14:50
thanks, we have been looking at managed sentry.

for now though, i think what we would like to understand is whether it is possible to restart sentry in a way that the keys in redis are created once again, and the existing projects start working?

right now the only solution we have found is that newly created projects work alright , but not the existing ones for which the problem happened initially
