### ISSUE TITLE
"Unknown API Error" Sometimes it's been returned 502 Bad Gateway, Sometimes it's ok

### ISSUE THREAD

**Issue by termhmt** [getsentry/onpremise#749] opened 2020-11-18 06:51 UTC
## Version Information

Version: *Latest*

## Description

"Unknown API Error" Sometimes it's been returned 502 Bad Gateway, Sometimes it's ok

## Steps to Reproduce

1. Search something like "user_id_login:137"
2. Enter
3. and so on.

## Logs

Please share any applicable logs:

![image](https://user-images.githubusercontent.com/4049102/99495176-d3d10b80-29a4-11eb-8716-371bca584683.png)
![image](https://user-images.githubusercontent.com/4049102/99495392-29a5b380-29a5-11eb-9dab-e41f6c9874dd.png)

**Comment by BYK** [comment] 2020-11-18 17:48
Hi @termhmt,

I'll be closing this issue as it does not follow the issue template and lacks important information for us to identify what the issue is. Specifically:

1. _Latest_ is not a valid version as it is a moving target. You need to specify the exact version you are using
2. You have not mentioned how you run Sentry. From your logs it seems like it is self-hosted but even then you need to mention whether you are using our onpremise repo or any custom setup you may have.
3. The logs you shared are cropped screenshots not giving the full context around the issue. We'll need the full logs of all services to be able to identify the issues.

Feel free to submit a new issue with the complete information we ask in the template.

**Closed by BYK** 2020-11-18 17:48 UTC
