### ISSUE TITLE
Can't setup sentry on docker - relation "sentry_option" does not exist.

### ISSUE THREAD

**Issue by aktywnitu** [getsentry/onpremise#154] opened 2019-02-22 09:47 UTC
```
tom@server:/opt/SENTRY/onpremise$ docker-compose run --rm web upgrade
Starting onpremise_redis_1     ... done
Starting onpremise_smtp_1      ... done
Starting onpremise_postgres_1  ... done
Starting onpremise_memcached_1 ... done
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/options/store.py", line 165, in get_store
    value = self.model.objects.get(key=key.name).value
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 123, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 80, in inner
    raise_the_exception(self.db, e)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 78, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 101, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 94, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 47, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: ProgrammingError('relation "sentry_option" does not exist\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\n                                                             ^\n',)
SQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."key" = %s 
09:45:09 [ERROR] sentry: option.failed-lookup (key=u'github.apps-install-url')
Top level Sentry exception caught - failed creating log record
option.failed-lookup
Traceback (most recent
```

**Comment by mattrobenolt** [comment] 2019-02-22 17:01
This is likely a false positive since that error is kinda expected and harmless. Does it continue on and eventually finish? You have the rest of the output cut off, so I can't tell.

**Comment by SuigetsuSake** [comment] 2019-03-22 10:26
I also have the same error and it doesn't sound like a false positive since once i `docker-compose up -d` then go to the login page, it crashes with an error.

Error on upgrade:
```
ProgrammingError: ProgrammingError('relation "sentry_option" does not exist\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\n                                                             ^\n',)
SQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."key" = %s 
10:05:37 [ERROR] sentry: option.failed-lookup (key=u'github.apps-install-url')
Top level Sentry exception caught - failed creating log record
```
Docker: Docker version 18.06.1-ce, build e68fc7a
Docker Compose: docker-compose version 1.22.0, build f46880f
Git log: master@cd13427aa9a231b2b27c9fd14017d183cca52c1e
System: macOS Moyave 10.14

Steps:
- `docker volume create --name=sentry-data && docker volume create --name=sentry-postgres`
- `cp -n .env.example .env`
- `docker-compose build`
- `docker-compose run --rm web config generate-secret-key` > copy result to .env file
- `docker-compose run --rm web upgrade` [upgrade_logs.txt (https://github.com/getsentry/onpremise/files/2996032/upgrade_logs.txt)
- First upgrade hasn't finished so launch a second one: `docker-compose run --rm web upgrade` [upgrade_logs_2.txt](https://github.com/getsentry/onpremise/files/2996031/upgrade_logs_2.txt)
- no user creation was asked so create it manually: `docker-compose run --rm web sentry createuser`  [create_user_logs.txt](https://github.com/getsentry/onpremise/files/2996029/create_user_logs.txt)
- `docker-compose up -d`
- Go to `http://localhost:9000` [login_page_logs.txt](https://github.com/getsentry/onpremise/files/2996030/login_page_logs.txt)



`

**Comment by SuigetsuSake** [comment] 2019-03-22 15:25
Ok, so from what has been said in #108 i tried giving more RAM to Docker for Mac and with 3GB RAM and 3GB swap, the first upgrade now finishes correctly and everything works 👏

**Comment by mattrobenolt** [comment] 2019-04-28 17:31
Closing since the issue isn’t really an issue for us. The need of a lot of RAM during initial migrations is known and something we’re looking to address, but it’d be outside of this repository.

**Closed by mattrobenolt** 2019-04-28 17:31 UTC
